name: Continuous Integration
on:
  push:
    branches:
      - main
      - 'EXP-**'
jobs:
  call-continuous-integration-reusable:
    uses: Nageshadevops/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project_name: expense-backend
      npm_install: true
    secrets: inherit
